services:
  # ---------------------------------------------------------
  # Auth Service
  # ---------------------------------------------------------
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SERVER_PORT=8080
    networks:
      - traveling-network

  # ---------------------------------------------------------
  # Planning Service
  # ---------------------------------------------------------
  planning-service:
    build:
      context: .
      dockerfile: planning-service/Dockerfile
    container_name: planning-service
    ports:
      - "8081:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      # To connect to auth-service within the same network
#      - AUTH_SERVICE_URL=http://auth-service:8080
#    depends_on:
#      - auth-service
    networks:
      - traveling-network

networks:
  traveling-network:
    driver: bridge