services:
  # ---------------------------------------------------------
  # MySQL Service
  # ---------------------------------------------------------
  mysql-db:
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASS}

  # ---------------------------------------------------------
  # RabbitMQ Service
  # ---------------------------------------------------------
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  # ---------------------------------------------------------
  # Auth Service
  # ---------------------------------------------------------
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MYSQL_URL=jdbc:mysql://mysql-db:3306/auth_dev?createDatabaseIfNotExist=true
      - MYSQL_PASS=${MYSQL_PASS}
      - SPRING_RABBITMQ_HOST=rabbitmq
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - PRIVATE_KEY_BASE64=${PRIVATE_KEY_BASE64}
      - PUBLIC_KEY_BASE64=${PUBLIC_KEY_BASE64}
    depends_on:
      mysql-db:
        condition: service_healthy

  # ---------------------------------------------------------
  # Planning Service
  # ---------------------------------------------------------
  planning-service:
    build:
      context: .
      dockerfile: planning-service/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MYSQL_URL=jdbc:mysql://mysql-db:3306/planning_dev?createDatabaseIfNotExist=true
      - MYSQL_PASS=${MYSQL_PASS}
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      mysql-db:
        condition: service_healthy

  # ---------------------------------------------------------
  # Social Service
  # ---------------------------------------------------------
  social-service:
    build:
      context: .
      dockerfile: social-service/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MYSQL_URL=jdbc:mysql://mysql-db:3306/social_dev?createDatabaseIfNotExist=true
      - MYSQL_PASS=${MYSQL_PASS}
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      mysql-db:
        condition: service_healthy