services:
  # ---------------------------------------------------------
  # MySQL Service
  # ---------------------------------------------------------
  mysql-db:
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASS}

  # ---------------------------------------------------------
  # RabbitMQ Service
  # ---------------------------------------------------------
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  # ---------------------------------------------------------
  # Auth Service
  # ---------------------------------------------------------
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:mysql://mysql-db:3306/auth_prod
      - DB_USER=root
      - DB_PASS=${MYSQL_PASS}
      - DB_DRIVER=${MYSQL_DRIVER}
      - HIBERNATE_DIALECT=${MYSQL_HIBERNATE_DIALECT}
      - SPRING_RABBITMQ_HOST=rabbitmq
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - PRIVATE_KEY_BASE64=${PRIVATE_KEY_BASE64}
      - PUBLIC_KEY_BASE64=${PUBLIC_KEY_BASE64}
    depends_on:
      mysql-db:
        condition: service_healthy

  # ---------------------------------------------------------
  # Planning Service
  # ---------------------------------------------------------
  planning-service:
    build:
      context: .
      dockerfile: planning-service/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:mysql://mysql-db:3306/planning_prod
      - DB_USER=root
      - DB_PASS=${MYSQL_PASS}
      - DB_DRIVER=${MYSQL_DRIVER}
      - HIBERNATE_DIALECT=${MYSQL_HIBERNATE_DIALECT}
      - SPRING_RABBITMQ_HOST=rabbitmq
      - RABBITMQ_URL=${RABBITMQ_URL}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - PUBLIC_KEY_BASE64=${PUBLIC_KEY_BASE64}
    depends_on:
      mysql-db:
        condition: service_healthy

  # ---------------------------------------------------------
  # Social Service
  # ---------------------------------------------------------
  social-service:
    build:
      context: .
      dockerfile: social-service/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:mysql://mysql-db:3306/social_prod
      - DB_USER=root
      - DB_PASS=${MYSQL_PASS}
      - DB_DRIVER=${MYSQL_DRIVER}
      - HIBERNATE_DIALECT=${MYSQL_HIBERNATE_DIALECT}
      - SPRING_RABBITMQ_HOST=rabbitmq
      - RABBITMQ_URL=${RABBITMQ_URL}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - PUBLIC_KEY_BASE64=${PUBLIC_KEY_BASE64}
    depends_on:
      mysql-db:
        condition: service_healthy