apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app.kubernetes.io/part-of: traveling-helper
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: database
    app.kubernetes.io/name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None