apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app.kubernetes.io/part-of: traveling-helper
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: database
    app.kubernetes.io/name: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi