spring:
  profiles:
    include: secrets
  application:
    name: auth
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - email
              - profile
      resourceserver:
        jwt:
          public-key-location: classpath:certs/public_key.pem