apiVersion: v1
kind: ConfigMap
metadata:
  name: traveling-helper-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  DB_DRIVER: "com.mysql.cj.jdbc.Driver"
  HIBERNATE_DIALECT: "org.hibernate.dialect.MySQLDialect"
  DB_USER: "root"
  SPRING_RABBITMQ_HOST: "rabbitmq-service" 
  MYSQL_HOST: "mysql-service"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"